### ISSUE TITLE
Mini Hackathon Text Is Weird

### ISSUE THREAD

**Issue by mzrimsek** [hacksu/Website#25]
Probably change to something like...

"Hey Hackers!

We all had a lot of fun last semester with a mini-hackathon, so we're doing it again. Here's what's going to happen. Everyone will break up into groups and then you'll have about an hour to make something based on a couple random words we'll give as a prompt."

I'd fork and submit a PR but this feels like a real small change and I don't feel like setting up the project on my laptop right now.

**Comment by IAPark** [comment]
Fair enough. I'm in the middle of trying to refactor a bunch of stuff and set up a proper back end to make this stuff easier to update. Apologies for the typos. It was intended originally as filler text and one day we just decided to put it up and didn't go over the events as carefully as we should have.

**Comment by IAPark** [comment]
Sorry this took so long. Last night I wrapped up setting up a proper backend to let us edit the events without changing the site itself. I've basically implemented the changes you wanted. If you still don't like it the good news is that it's easy to change now.
